package com.carusato.restapi.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for User domain entity.
 * Tests immutability and builder pattern.
 */
@DisplayName("User Domain Entity Unit Tests")
class UserTest {
    
    @Test
    @DisplayName("Should create user with builder successfully")
    void shouldCreateUserWithBuilderSuccessfully() {
        // Act
        User user = new User.Builder()
                .id(1L)
                .username("john_doe")
                .age(30)
                .active(true)
                .build();
        
        // Assert
        assertThat(user)
                .isNotNull()
                .extracting(User::getId, User::getUsername, User::getAge, User::isActive)
                .containsExactly(1L, "john_doe", 30, true);
    }
    
    @Test
    @DisplayName("Should create user with default active status")
    void shouldCreateUserWithDefaultActiveStatus() {
        // Act - active defaults to true
        User user = new User.Builder()
                .id(1L)
                .username("jane_doe")
                .age(25)
                .build();
        
        // Assert
        assertThat(user.isActive()).isTrue();
    }
    
    @Test
    @DisplayName("Should create inactive user")
    void shouldCreateInactiveUser() {
        // Act
        User user = new User.Builder()
                .id(1L)
                .username("john_doe")
                .age(30)
                .active(false)
                .build();
        
        // Assert
        assertThat(user.isActive()).isFalse();
    }
    
    @Test
    @DisplayName("Should get user properties correctly")
    void shouldGetUserPropertiesCorrectly() {
        // Arrange
        Long expectedId = 1L;
        String expectedUsername = "john_doe";
        Integer expectedAge = 30;
        boolean expectedActive = true;
        
        // Act
        User user = new User.Builder()
                .id(expectedId)
                .username(expectedUsername)
                .age(expectedAge)
                .active(expectedActive)
                .build();
        
        // Assert
        assertThat(user.getId()).isEqualTo(expectedId);
        assertThat(user.getUsername()).isEqualTo(expectedUsername);
        assertThat(user.getAge()).isEqualTo(expectedAge);
        assertThat(user.isActive()).isEqualTo(expectedActive);
    }
    
    @Test
    @DisplayName("Should create user without ID (for new users)")
    void shouldCreateUserWithoutId() {
        // Act - ID can be null for new users (will be generated by DB)
        User user = new User.Builder()
                .username("new_user")
                .age(25)
                .active(true)
                .build();
        
        // Assert
        assertThat(user.getId()).isNull();
        assertThat(user.getUsername()).isEqualTo("new_user");
        assertThat(user.getAge()).isEqualTo(25);
    }
    
    @Test
    @DisplayName("Should handle all age values correctly")
    void shouldHandleAllAgeValuesCorrectly() {
        // Test age 0
        User userAge0 = new User.Builder()
                .id(1L)
                .username("baby")
                .age(0)
                .build();
        
        // Test age 150
        User userAge150 = new User.Builder()
                .id(2L)
                .username("elder")
                .age(150)
                .build();
        
        // Test age in middle
        User userAgeMiddle = new User.Builder()
                .id(3L)
                .username("adult")
                .age(50)
                .build();
        
        // Assert
        assertThat(userAge0.getAge()).isZero();
        assertThat(userAge150.getAge()).isEqualTo(150);
        assertThat(userAgeMiddle.getAge()).isEqualTo(50);
    }
    
    @Test
    @DisplayName("Should be immutable - cannot modify properties after creation")
    void shouldBeImmutable() {
        // Act
        User user = new User.Builder()
                .id(1L)
                .username("john_doe")
                .age(30)
                .active(true)
                .build();
        
        // Assert - User fields are final, so they cannot be modified
        // This is enforced at compile time, not runtime
        assertThat(user)
                .hasFieldOrPropertyWithValue("id", 1L)
                .hasFieldOrPropertyWithValue("username", "john_doe")
                .hasFieldOrPropertyWithValue("age", 30)
                .hasFieldOrPropertyWithValue("active", true);
    }
    
    @Test
    @DisplayName("Should support multiple builder instances without interference")
    void shouldSupportMultipleBuilderInstancesWithoutInterference() {
        // Act
        User user1 = new User.Builder()
                .id(1L)
                .username("user1")
                .age(25)
                .build();
        
        User user2 = new User.Builder()
                .id(2L)
                .username("user2")
                .age(35)
                .build();
        
        // Assert
        assertThat(user1)
                .extracting(User::getId, User::getUsername, User::getAge)
                .containsExactly(1L, "user1", 25);
        
        assertThat(user2)
                .extracting(User::getId, User::getUsername, User::getAge)
                .containsExactly(2L, "user2", 35);
    }
}

